version: '3.4'
services:
  helloworld-cm-share:
    image: alfresco-share-helloworld-cm:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../helloworld-cm-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: helloworld-cm-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  helloworld-cm-acs:
    image: alfresco-content-services-helloworld-cm:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../helloworld-cm-platform-docker/target
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      JAVA_OPTS: "-Dmessaging.broker.url=\"failover:(nio://helloworld-cm-activemq:61616)?timeout=3000&jms.useCompression=true\""
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - helloworld-cm-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - helloworld-cm-postgres
  helloworld-cm-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - helloworld-cm-db-volume:/var/lib/postgresql/data
  helloworld-cm-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: helloworld-cm-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: helloworld-cm-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - helloworld-cm-ass-volume:/opt/alfresco-search-services/contentstore
      - helloworld-cm-ass-volume:/opt/alfresco-search-services/data
  helloworld-cm-activemq:
    image: alfresco/alfresco-activemq:5.16.1
    ports:
      - 8161:8161 # Web Console
      - 5672:5672 # AMQP
      - 61616:61616 # OpenWire
      - 61613:61613 # STOMP 

  helloworld-cm-tsgaca:
    image: tsgaca
    ports: 
      - "${tsgaca.port}:8080"
    depends_on:
      - helloworld-cm-acs

volumes:
  helloworld-cm-acs-volume:
    external: true
  helloworld-cm-db-volume:
    external: true
  helloworld-cm-ass-volume:
    external: true
